WebApplicationAccommodation/Models/Category.cs
namespace WebApplicationAccommodation.Models
{
    public class Category
    {
        //create all the properties you want on the tabel eg ID, name etc

        public int Id { get; set; }
        public int DisplayOrder { get; set; }
        public DateTime CreatedDateTime { get; set; } = DateTime.Now;
}
}

WebApplicationAccommodation/Models/ErrorViewModel.cs
namespace WebApplicationAccommodation.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplicationAccommodation/Models/PriceViewModel.cs
namespace WebApplicationAccommodation.Models
{
    public class PriceViewModel
    {
        public string Name { get; set; }
    }
}

WebApplicationAccommodation/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApplicationAccommodation.Controllers
{
    public class CategoryController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

    }
}

WebApplicationAccommodation/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApplicationAccommodation.Models;

namespace WebApplicationAccommodation.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplicationAccommodation/Controllers/SecondController.cs
using Microsoft.AspNetCore.Mvc;

using WebApplicationAccommodation.Models;

namespace WebApplicationAccommodation.Controllers
{
    public class SecondController : Controller
    {
        public IActionResult Index()
        {
            return View();

            PriceViewModel priceView = new PriceViewModel() { Name = "Sif" };
            return View(priceView);
        }

        public IActionResult Create()
        {
            var priceVm = new PriceViewModel();
            return View(priceVm);
        }

        public IActionResult CreatePrice(PriceViewModel price)
        {
            return View("Index");
        }
    }
}

WebApplicationAccommodation/Views/Category/About.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

WebApplicationAccommodation/Views/Category/Index.cshtml
@model PriceViewModel

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Guest Queries</h1>


<div class="row">

	<div class="col-12">

		<div class="card">
			<div class="card-header">
				<h5>Create a Query</h5>
			</div>

			<div class="card-body">
				<form asp-controller="Second" asp-action="CreatePrice" method="post">
					<div class="mb-3"> 
						<label class="form-label">Full Name</label>
						<input asp-for=Name type="text" class="form-control" />
					</div>

					<div class="mb-3"> 
						<label class="form-label">Phone Number</label>
						<input asp-for=Name type="text" class="form-control" />
					</div>

					<div class="mb-3"> 
						<label class="form-label">Question:</label>
						<input asp-for=Name type="text" class="form-control" />
					</div>

					<div> 
						<label class="form-label">Dates of Stay</label>
						<input type="datetime" class="form-control"/>
					</div>

					<div class="mb-3">
						<button type="submit" class="btn btn-primary">Submit Form</button>
					</div>

					<div class="mb-3"> 
						<label class="form-label">Email</label>
						<input asp-for=Name type="text" class="form-control" />
					</div>


					<div class="mb-3"> 
						<label class="form-label">Reservation</label>
						<input asp-for=Name type="text" class="form-control" />
					</div>

				</form>
			</div>	

			<div class="card-footer">

			</div>

		</div>

	</div>

</div>

WebApplicationAccommodation/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebApplicationAccommodation/Views/Second/Create.cshtml
@model PriceViewModel

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Luxury Accommodation</h1>


<div class="row">

	<div class="col-12">

		<div class="card">
			<div class="card-header">
			</div>
			 <h2>create booking</h2>
			<div class="card-body">
				<form asp-controller="Second" asp-action="CreatePrice" method="post">
					<div class="mb-3"> 
						<label class="form-label">Full Name</label>
						<input asp-for=Name type="text" class="form-control" />
					</div>

					<div class="mb-3"> 
						<label class="form-label">Phone Number</label>
						<input asp-for=Name type="text" class="form-control" />
					</div>

					<div class="mb-3"> 
						<label class="form-label">Email Address</label>
						<input asp-for=Name type="text" class="form-control" />
					</div>

					<div> 
						<label class="form-label">Payment Options</label>
						<input type="number" class="form-control"/>
					</div>

					<div> 
						<label class="form-label">Number of nights</label>
						<input type="number" class="form-control"/>
					</div>

					<div> 
						<label class="form-label">DAtES</label>
						<input type="number" class="form-control"/>
					</div>

					<div> 
						<label class="form-label">Number of Guests</label>
						<input type="number" class="form-control"/>
					</div>

					<div class="mb-3">
						<button type="submit" class="btn btn-primary">Submit Form</button>
					</div>
				</form>
			</div>	

			<div class="card-footer">

			</div>

		</div>

	</div>

</div>

WebApplicationAccommodation/Views/Second/Index.cshtml
@model WebApplicationAccommodation.Models.PriceViewModel

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<main class="grid-container">
        
    <h1>Luxury Accommodation</h1>
    <p>Hotel Room:</p>
    <p>Hotel Room:</p>
    

   <br />
   <div class="row">
      <div class="col-sm-9"><div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
      </div>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="https://imgix.theurbanlist.com/content/article/voco_Auckland_City_Centre_room_view.jpg" class="d-block w-100" alt="...">
          <div class="carousel-caption d-none d-md-block">
            <h5>King Size Bed</h5>
            <p>Some representative placeholder content for the first slide.</p>
          </div>
        </div>
        <div class="carousel-item">
          <img src="https://imgix.theurbanlist.com/content/article/voco_Auckland_City_Centre_room_view.jpg" class="d-block w-100" alt="...">
          <div class="carousel-caption d-none d-md-block">
            <h5>Second slide label</h5>
            <p>Some representative placeholder content for the second slide.</p>
          </div>
        </div>
        <div class="carousel-item">
          <img src="..." class="d-block w-100" alt="...">
          <div class="carousel-caption d-none d-md-block">
            <h5>Third slide label</h5>
            <p>Some representative placeholder content for the third slide.</p>
          </div>
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
   </div></div>
      <div class="col-sm-3"><div id="calendar">
        <table>
            <thead>
                <tr> 
                    <th>Sun</th>
                    <th>Mon</th>
                    <th>Tue</th>
                    <th>Wed</th>
                    <th>Thu</th>
                    <th>Fri</th>
                    <th>Sun</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td class="booked"></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>1</td>
                    <td>2</td>
                </tr>
                <tr>
                    <td>3</td>
                    <td>4</td>
                    <td>5</td>
                    <td>6</td>
                    <td>7</td>
                    <td>8</td>
                    <td>9</td>
                </tr>
                <tr>
                    <td>10</td>
                    <td class="booked"></td>
                    <td>12</td>
                    <td></td>
                    <td>1</td>
                    <td>2</td>
                </tr>
               <tr>
                    <td>3</td>
                    <td>4</td>
                    <td>5</td>
                    <td>6</td>
                    <td>7</td>
                    <td>8</td>
                    <td>9</td>
                </tr>

                <tr>
                    <td>1</td>
                    <td>1</td>
                    <td>1</td>
                    <td>1</td>
                    <td>1</td>
                    <td>1</td>
                    <td>1</td>
                </tr>
            </tbody>
        </table>
        <br />

        <p class="price">NZD 490</p>
        <br />
                    <div class="btn">
                        <div class="space2" ><button type="submit" class="btn btn-primary"> Book </button></div>
                        <div class="space" ><button type="submit" class="btn btn-danger">Queries</button></div>
					</div>

            @*<form asp-controller="Second" asp-action="Create" method="post">
					<div class="btn1" class="mb-3">
						<button type="submit" class="btn btn-primary">Save</button>
                        <button id="btn" type="submit" class="btn btn-primary">Save</button>
					</div>
    
				</form>*@

    </div>
    </div>
    </div>

    <br />

    <section class="gallery min-vh-100">
        <div class="container-lg">
            <div class="row gy-4 row-cols-1 row-cols-sm-2 row-cols-md-3">
                    <div class="col">
                        <img src="https://imgix.theurbanlist.com/content/article/voco_Auckland_City_Centre_room_view.jpg" class="gallery-item" />
                    </div>
                    <div class="col">
                        <img src="https://imgix.theurbanlist.com/content/article/voco_Auckland_City_Centre_room_view.jpg" class="gallery-item" />
                    </div>
                    <div class="col">
                        <img src="https://imgix.theurbanlist.com/content/article/voco_Auckland_City_Centre_room_view.jpg" class="gallery-item" />
                    </div>
                    <div class="col">
                        <img src="https://imgix.theurbanlist.com/content/article/voco_Auckland_City_Centre_room_view.jpg" class="gallery-item" />
                    </div>
                    <div class="col">
                        <img src="https://imgix.theurbanlist.com/content/article/voco_Auckland_City_Centre_room_view.jpg" class="gallery-item" />
                    </div>
                    <div class="col">
                        <img src="https://imgix.theurbanlist.com/content/article/voco_Auckland_City_Centre_room_view.jpg" class="gallery-item" />
                    </div>

            </div>
        </div>
    </section>

<!-- Modal -->
<div class="modal fade" id="gallery-modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        @*<h5 class="modal-title" id="exampleModalLabel">Modal title</h5>*@
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <img src="https://imgix.theurbanlist.com/content/article/voco_Auckland_City_Centre_room_view.jpg" class="modal-img" />
      </div>
    </div>
  </div>
</div>


   <div class="row">
      <div class="col-sm-3">.</div>
      <div class="col-sm-3">.</div>
      <div class="col-sm-3">.col-sm-3</div>
      <div class="col-sm-3">.col-sm-3</div>
    </div>
   <br />
    
   <!-- Button trigger modal -->
<img src="https://imgix.theurbanlist.com/content/article/voco_Auckland_City_Centre_room_view.jpg" class="gall-img" data-bs-toggle="modal" data-bs-target="#exampleModal">

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <img src="https://imgix.theurbanlist.com/content/article/voco_Auckland_City_Centre_room_view.jpg" />
      </div>
    </div>
  </div>
</div>


</main>

<br />

WebApplicationAccommodation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplicationAccommodation</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/Stylesheet.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/StyleSheet.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplicationAccommodation.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-danger border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Second" asp-action="Index">HOMEPAGE</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Second" asp-action="Create">BOOK</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">QUERIES</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="About">ABOUT</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="About">Information</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebApplicationAccommodation - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>